version: '3.8'

services:
  app:
    image: php:8.2-apache
    container_name: data_modeler_app
    restart: always
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - codeigniter-network

  mongo:
    image: mongo:latest
    container_name: data_modeler_db
    restart: always
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - codeigniter-network

volumes:
  mongo-data:
    driver: local

networks:
  codeigniter-network:
    driver: bridge