version: '3.8'

services:
  app:
    build: .
    container_name: codeigniter_app
    restart: always
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
    networks:
      - codeigniter-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: codeigniter_mongo
    restart: always
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - codeigniter-network

volumes:
  mongo-data:
    driver: local

networks:
  codeigniter-network:
    driver: bridge